// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run against the unpooled connection. Neon's pooler runs in
    // transaction mode, which doesn't support the advisory locks and session
    // features Prisma Migrate needs. The app's runtime client uses the pooled
    // DATABASE_URL instead, read directly via a driver adapter.
    url: process.env["DIRECT_URL"],
  },
});
